language: scala
scala:
  - "2.10.2"
jdk:
  - oraclejdk7

branches:
  only:
    - master

notifications:
  email:
    - freeman.wes@gmail.com
    - jasonjackson@gmail.com

before_install:
  - wget dist.neo4j.org/neo4j-community-2.0.0-unix.tar.gz
  - tar -xzf neo4j-community-2.0.0-unix.tar.gz
  - neo4j-community-2.0.0/bin/neo4j start
