language: scala
scala:
  - "2.10.3"
jdk:
  - oraclejdk7
  
env:
  - NEO_VERSION="2.0.0"

branches:
  only:
    - master

notifications:
  email:
    - freeman.wes@gmail.com
    - jasonjackson@gmail.com

before_install:
  - wget dist.neo4j.org/neo4j-community-$NEO_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz
  - neo4j-community-$NEO_VERSION/bin/neo4j start

after_success:
  - sbt coveralls
