language: scala
scala:
  - "2.9.2"
jdk:
  - oraclejdk7
  - oraclejdk6
  - openjdk7
  - openjdk6

branches:
  only:
    - master

notifications:
  email:
    - freeman.wes@gmail.com

services:
  - neo4j
